name: 'Image to avif'
description: 'use node js prower convent image such as jpeg file to avif image file where github action.'
inputs:
    who-to-greet:  'okaku'
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
